export const dataVariables ={
    
 FETCH_DATA_REQUEST :'FETCH_DATA_REQUEST', 
 FETCH_DATA_SUCCESS : 'FETCH_DATA_SUCCESS',
 FETCH_DATA_FAILURE : 'FETCH_DATA_FAILURE',
}


export const cartVariables ={
    ADD_TO_CART :"ADD_TO_CART",
    REMOVE_ITEMS:"REMOVE_TO_CART"
}